#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            2
bspc config focused_border_color    "#7D0053"
bspc config window_gap              12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# AutoStart applications
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/Pictures/art/foxes/fox-under-stars.jpg
dunst &
