#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# if connected to multiple monitors make dual screen
if [[ $(xrandr -q | grep " connected" | cut -d" " -f2 | wc -c) -gt 10 ]]; then
    # this stuff is unique for every computer
    xrandr --output eDP-1-1 --primary --output HDMI-0 --mode 1920x1080 --right-of eDP-1-1
    bspc monitor eDP-1-1 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
    bspc wm -O eDP-1-1 HDMI-0 
else
    bspc monitor -d I II III IV V
fi

bspc config border_width            2
bspc config focused_border_color    "#7D0053"
bspc config window_gap              12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blueberry.py state=floating
bspc rule -a Nm-connection-editor state=floating

# AutoStart applications
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/Pictures/art/foxes/fox-under-stars.jpg
dunst &
$HOME/.config/polybar/launch-polybar.sh
