#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# if connected to multiple monitors make dual screen
if [[ $(xrandr -q | grep " connected" | cut -d" " -f2 | wc -c) -gt 10 ]]; then
    # this stuff is unique for every computer
    xrandr --output eDP-1-1 --primary --output HDMI-0 --mode 1920x1080 --rate 144 --right-of eDP-1-1
    bspc monitor eDP-1-1 -d VI VII VIII IX X
    bspc monitor HDMI-0 -d I II III IV V
    bspc wm -O HDMI-0 eDP-1-1
else
    bspc monitor -d I II III IV V
fi

bspc config border_width            2
bspc config focused_border_color    "#7D0053"
bspc config window_gap              12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blueberry.py state=floating
bspc rule -a Nm-connection-editor state=floating

# AutoStart applications
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/Pictures/foxroom.png
dunst &
$HOME/.config/polybar/launch-polybar.sh &

if [[ $(ps -e | grep "Discord" | wc -c) -eq 0 ]]; then
    discord --start-minimized &
fi
if [[ $(ps -e | grep "steam" | wc -c) -eq 0 ]]; then
    steam -nochatui -nofriendsui -silent &
fi
if [[ $(ps -e | grep "openrgb" | wc -c) -eq 0 ]]; then
    openrgb --startminimized &
fi
