#!/bin/bash

# checks is powered: yes in in the output and compares wordcount to 0
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
    echo "󰂲"
# checks if theres a device connected if so returns true
elif [ $(echo info | bluetoothctl | grep "DeviceSet" | wc -c) -eq 0 ]
then
    echo "%{F#71EBFB}󰂯"
else
    echo "󰂯"
fi
